version: 2

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

submodules:
  include: all

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - graphviz
